### ISSUE TITLE
reload_data.py

### ISSUE THREAD

**Issue by Pandade1997** [yzyouzhang/AIR-ASVspoof#15]
What is path_to_mat in reload_data.py？

**Comment by Pandade1997** [comment]
I am a bit confused what is the purpose of reload_data.py?

**Comment by yzyouzhang** [comment]
Hi, Thank you for your questions. The "path_to_mat" is the directory of the .mat files that you generated when running process_LA_data.m. The purpose of reload_data.py is to convert the .mat files to .pkl files so that it is easier for python to process. Hope it helps. Feel free to raise further questions.

**Comment by Pandade1997** [comment]
> 嗨，谢谢您的提问。“ path_to_mat”是您在运行process_LA_data.m时生成的.mat文件的目录。reload_data.py的目的是将.mat文件转换为.pkl文件，以便python更容易处理。希望能帮助到你。随时提出进一步的问题。

Thank you for your answer, I am very interested in your work, it is very useful to me, thank you！

**Comment by yzyouzhang** [comment]
Thank you for your interest in our work! We welcome any further questions and communication. I will close this issue for now.
